config/routes.rb
Rails.application.routes.draw do
  root "dashboard#readme"
  patch "/dashboard/change_month/:month", to: "dashboard#change_month", as: "change_dashboard_month"
  get "/dashboard", to: "dashboard#show"

  resources :expenses, only: :index do
    member { patch :approve, :reject, :pend }
  end

  resources :users, only: [:edit, :update]
  resources :exchange_rates, except: [:new, :show]

  namespace :current_user do
    resources :expenses, only: [:index, :create, :edit, :update, :destroy]
  end

  # In case this was linked to before the readme became the root_path
  get "/dashboard/readme", to: "dashboard#readme"
end

app/models/dashboard.rb
class Dashboard
  def initialize(user, date)
    @user = user
    @date = date
  end

  def rejected_count
    rejected_expenses.count
  end

  def pending_count
    pending_expenses.count
  end

  def approved_count
    approved_expenses.count
  end

  def rejected_total
    rejected_expenses.sum_in(currency)
  end

  def pending_total
    pending_expenses.sum_in(currency)
  end

  def approved_total
    expenses.for_month(month).approved.sum_in(currency)
  end

  def month
    year_month(date)
  end

  def previous_month
    date - 1.month
  end

  def next_month
    date + 1.month
  end

  def currency
    user.default_currency
  end

  private
  attr_reader :user, :date

  def expenses
    user.expenses
  end

  def rejected_expenses
    @rejected_expenses ||= expenses.rejected
  end

  def pending_expenses
    @pending_expenses ||= expenses.pending
  end

  def approved_expenses
    @approved_expenses ||= expenses.approved
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  delegate :number_with_precision, to: :view_context

  def show
    @dashboard = Dashboard.new(current_user, 1.month.ago)
  end

  def change_month
    month = Date.parse(params[:month])
    @dashboard = Dashboard.new(current_user, month)
  end

  def readme
  end

end

app/views/dashboard/_approved_card_stats.html.erb
<div class="card-stats">
  <ul>
    <li class="arrow">
      <%= link_to fa_icon('arrow-left'), change_dashboard_month_path(month: @dashboard.previous_month), method: :patch, remote: true, id: 'previous-month', class: 'change-month' %>
    </li>
    <li class="due">
      <%= number_with_precision @dashboard.approved_total, precision: 2 %> <span><%= @dashboard.currency %> (<%= @dashboard.month %>)</span>
    </li>
    <li class="arrow">
      <%= link_to fa_icon('arrow-right'), change_dashboard_month_path(month: @dashboard.next_month), method: :patch, remote: true, id: 'next-month', class: 'change-month' %>
    </li>
  </ul>
</div>

app/views/dashboard/change_month.js.erb
stats = $("#approved-card .card-stats");

stats.replaceWith("<%= j render "approved_card_stats" %>");

app/views/dashboard/readme.html.erb
<div id="readme">
  <%= markdown File.read('README.md') %>
</div>

app/views/dashboard/show.html.erb
<h1>Expenses dashboard</h1>
<hr></hr>

<div class="cards">
  <div id="rejected-card" class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png" alt="">
    </div>
    <div class="card-header">
      Rejected
    </div>
    <div class="card-copy">
      <p>Edit and resubmit these expenses before the 10th of the next month in order to claim a reimbursement on them.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li class="count   "><%= @dashboard.rejected_count %><span> <%= "Expense".pluralize(@dashboard.rejected_count) %></span></li>
        <li class="total   "><%= number_with_precision @dashboard.rejected_total, precision: 2 %><span> <%= @dashboard.currency %></span></li>
      </ul>
    </div>
  </div>

  <div id="pending-card" class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-4.png" alt="">
    </div>
    <div class="card-header">
      Pending
    </div>
    <div class="card-copy">
      <p>These expenses will be reviewed by your supervisor before the 10th of the next month.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li class="count   "><%= @dashboard.pending_count %><span> <%= "Expense".pluralize(@dashboard.pending_count) %></span></li>
        <li class="total   "><%= number_with_precision @dashboard.pending_total, precision: 2 %><span> <%= @dashboard.currency %></span></li>
      </ul>
    </div>
  </div>

  <div id="approved-card" class="card">
    <div class="card-image">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains-3.png" alt="">
    </div>
    <div class="card-header">
      Approved
    </div>
    <div class="card-copy">
      <p>These expenses have been approved by your supervisor and will be reimbursed by the 15th of the following month.</p>
    </div>
    <%= render 'approved_card_stats' %>
  </div>
</div>