config/routes.rb
Rails.application.routes.draw do
  root "dashboard#readme"
  patch "/dashboard/change_month/:month", to: "dashboard#change_month", as: "change_dashboard_month"
  get "/dashboard", to: "dashboard#show"

  resources :expenses, only: :index do
    member { patch :approve, :reject, :pend }
  end

  resources :users, only: [:edit, :update]
  resources :exchange_rates, except: [:new, :show]

  namespace :current_user do
    resources :expenses, only: [:index, :create, :edit, :update, :destroy]
  end

  # In case this was linked to before the readme became the root_path
  get "/dashboard/readme", to: "dashboard#readme"
end

app/controllers/api/v1/expenses_controller.rb
class Api::V1::ExpensesController < ApplicationController
  respond_to :json

  def index
    respond_with current_user.expenses.limit(10)
  end

  def review
    render json: ReviewExpensesDatatable.new(view_context)
  end

  def approve
    respond_with unscoped_expense.update(status: "Approved")
  end

  def reject
    respond_with unscoped_expense.update(status: "Rejected")
  end

  def pend
    respond_with unscoped_expense.update(status: "Pending")
  end

  def create
    respond_with current_user.expenses.create(expense_params)
    respond_with @expense.save
  end

  def destroy
    respond_with find_expense.destroy
  end

  def edit
    respond_with find_expense
  end

  def update
    respond_with find_expense.update(expense_params)
  end

  private

  def find_expense
    current_user.expenses.find(params[:id])
  end

  def unscoped_expense
    Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:date, :category_id, :description, :currency, :amount)
  end

end

app/controllers/current_user/expenses_controller.rb
module CurrentUser
  class ExpensesController < ApplicationController
    def index
      respond_to do |format|
        format.html
        format.json { @expenses = Datatable.new(params, UserExpenseSearch.new(current_user)) }
      end
    end

    def create
      @expense = current_user.expenses.build(expense_params)
      @expense.save
      render "create_or_update"
    end

    def destroy
      find_expense
      @expense.destroy!
    end

    def edit
      find_expense
    end

    def update
      find_expense
      @expense.update(expense_params)
      render "create_or_update"
    end

    private

    def find_expense
      @expense = current_user.expenses.find(params[:id])
    end

    def expense_params
      params.require(:expense).permit(:date, :category_id, :description, :currency, :amount)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { @expenses = Datatable.new(params, ExpensesSearch.new) }
    end
  end

  def approve
    change_expense_status("Approved")
  end

  def reject
    change_expense_status("Rejected")
  end

  def pend
    change_expense_status("Pending")
  end

  private

  def find_expense
    @expense = Expense.find(params[:id])
  end

  def change_expense_status(new_status)
    find_expense
    @expense.update!(status: new_status)
    render "update_status"
  end
end

app/views/current_user/expenses/_form.html.erb
<%= simple_form_for [:current_user, expense], remote: true do |f| %>
  <%= render "shared/errors", object: f.object %>
  <%= f.input :date, as: :string, wrapper_html: { class: "medium" }, input_html: { class: "datepicker" } %>
  <%= f.association :category, wrapper_html: { class: "medium" } %>
  <%= f.input :description, wrapper_html: { class: "large" } %>
  <%= f.input :currency, collection: ExchangeRate::CURRENCIES, required: true, wrapper_html: { class: "tiny" } %>
  <%= f.input :amount, wrapper_html: { class: "small" } %>
  <%= f.button :submit %>
<% end %>

app/views/current_user/expenses/_table.html.erb
<table id="expenses" class="datatable hover" data-source="<%= current_user_expenses_url(format: :json)%>">
  <thead>
    <tr>
      <td></td>
      <td>Date</td>
      <td>Category</td>
      <td>Description</td>
      <td>Currency</td>
      <td>Amount</td>
      <td>Status</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/current_user/expenses/create_or_update.js.erb
var table = $("table#expenses");
var form = $("form");

<% if @expense.errors.any? %>
  form.find(".errors").replaceWith("<%= j render "shared/errors", object: @expense %>");
<% else %>
  form.replaceWith("<%= j render "form", expense: Expense.new %>");
  table.DataTable().ajax.reload();
<% end %>

app/views/current_user/expenses/destroy.js.erb
var table = $("table#expenses");
table.DataTable().ajax.reload();

app/views/current_user/expenses/edit.js.erb
$("form").replaceWith("<%= j render "form", expense: @expense %>");

app/views/current_user/expenses/index.html.erb
<h1>My expenses</h1>

<hr></hr>
<%= render "form", expense: Expense.new %>
<br></br>
<%= render "table" %>