config/routes.rb
Rails.application.routes.draw do
  root "dashboard#readme"
  patch "/dashboard/change_month/:month", to: "dashboard#change_month", as: "change_dashboard_month"
  get "/dashboard", to: "dashboard#show"

  resources :expenses, only: :index do
    member { patch :approve, :reject, :pend }
  end

  resources :users, only: [:edit, :update]
  resources :exchange_rates, except: [:new, :show]

  namespace :current_user do
    resources :expenses, only: [:index, :create, :edit, :update, :destroy]
  end

  # In case this was linked to before the readme became the root_path
  get "/dashboard/readme", to: "dashboard#readme"
end

app/views/layouts/_nav.html.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="">
    </a>
    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <% if signed_in? %>
      <div class="nav">
        <ul id="navigation-menu">
          <li class="nav-link"><%= link_to "Read me", root_path %></li>
          <li class="nav-link"><%= link_to "Dashboard", dashboard_path %></li>
          <li class="nav-link"><%= link_to "My expenses", current_user_expenses_path %></li>
          <li class="nav-link"><%= link_to "All expenses", expenses_path %></li>
          <li class="nav-link"><%= link_to "Exchange rates", exchange_rates_path %></li>
          <li class="nav-link"><%= link_to "Profile", [:edit, current_user] %></li>
        </ul>
      </div>
      <div class="navigation-tools">
        <%= link_to 'Sign out', sign_out_path, :method => :delete, class: "sign-up" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "layouts/nav" %>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <div id="ember-app"></div>
</body>
</html>